In [ ]:
# solution of problem statement 1

In [1]:
import numpy as np

# Define the dimensions of the matrices
M, N, A = 3, 2, 4

# Create random matrices with the specified dimensions
matrix_M = np.random.rand(M, N)
matrix_NA = np.random.rand(N, A)

# Perform matrix multiplication
result_matrix = np.dot(matrix_M, matrix_NA)  # or matrix_M @ matrix_NA

# Print the result
print("Matrix M:")
print(matrix_M)
print("\nMatrix NA:")
print(matrix_NA)
print("\nMatrix Product (M x NA):")
print(result_matrix)

Matrix M:
[[0.70912022 0.0977243 ]
 [0.82284962 0.43796171]
 [0.22243178 0.62091695]]

Matrix NA:
[[0.2449688  0.9066801  0.9305449  0.60760599]
 [0.73669342 0.15561103 0.68281017 0.41524456]]

Matrix Product (M x NA):
[[0.24570518 0.65815216 0.72659534 0.47144517]
 [0.52421599 0.81421304 1.06474322 0.68182958]
 [0.51191428 0.298296   0.63095117 0.39298327]]


In [ ]:
# solution of problem statement 2

In [2]:
import numpy as np

# Define a function to check if a string is composed of digits, lowercase, and uppercase letters
def is_valid(s):
    return all(c.isdigit() or c.islower() or c.isupper() for c in s)

# Create an original array
original_array = np.array(['Python', 'PHP', 'JS', 'Examples', 'html5', '5'])

# Use np.vectorize to apply the is_valid function to each element in the array
is_valid_element = np.vectorize(is_valid)(original_array)

# Print the original array and the corresponding boolean result
print("Original Array:")
print(original_array)
print("\nIs each element composed of digits, lowercase, and uppercase letters only?")
print(is_valid_element)

Original Array:
['Python' 'PHP' 'JS' 'Examples' 'html5' '5']

Is each element composed of digits, lowercase, and uppercase letters only?
[ True  True  True  True  True  True]


In [ ]:
# solution of problem statement 3

In [4]:
import numpy as np

# Step 1: Read input values for X and Y
X, Y = map(int, input().split())

# Step 2: Create lists lst1 and lst2
lst1 = list(range(1, 16 * X + 1, X))
lst2 = list(range(1, 16 * Y + 1, Y))

# Step 3: Create NumPy arrays np1 and np2
np1 = np.array(lst1)
np2 = np.array(lst2)

# Step 4: Reshape both NumPy arrays to (4, 4)
np1 = np1.reshape(4, 4)
np2 = np2.reshape(4, 4)

# Step 5: Create a new NumPy array np3 by subtracting np2 from np1
np3 = np1 - np2

# Step 6: Print the elements of np3 in a single dimension list
print(np3.flatten().tolist())


9 12
[0, -3, -6, -9, -12, -15, -18, -21, -24, -27, -30, -33, -36, -39, -42, -45]


In [ ]:
# solution of problem statement 4

In [7]:
import numpy as np

# Step 1: Read the elements of matrices P and Q from the user
elements_P = list(map(int, input().split()))
elements_Q = list(map(int, input().split()))

# Step 2: Create NumPy arrays P and Q with shape [3, 3]
P = np.array(elements_P).reshape(3, 3)
Q = np.array(elements_Q).reshape(3, 3)

# Step 3: Calculate the element-wise difference (P - Q)
result = P - Q

# Step 4: Print the result
for row in result:
    print(row)

1 2 3 4 5 6 7 8 9
11 22 33 44 55 66 77 88 99
[-10 -20 -30]
[-40 -50 -60]
[-70 -80 -90]
